framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cache: null

        # Utiliser APCu pour tous les environnements
        app: cache.adapter.apcu
        system: cache.adapter.apcu
        
        # Configurer des pools de cache sp√©cifiques pour Doctrine
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
            doctrine.metadata_cache_pool:
                adapter: cache.system

when@dev:
    framework:
        cache:
            # Utiliser APCu au lieu du filesystem
            app: cache.adapter.apcu
            system: cache.adapter.apcu
            # Define common cache pools
            pools:
                doctrine.system_cache_pool:
                    adapter: cache.system
